# Generated by Django 4.0.6 on 2022-07-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='For_polls', to='Interview.poll', verbose_name='Опрос'),
        ),
    ]
